120036 cfg custom unmarshaling
coopnorge/go-datadog-lib pull request #301
Opened 2024-02-26 13:45 UTC by LinMAD

Add support to `DatadogConfig` to work with Golang vanilla JSON tags.
Issue related to bool type in DatadogConfig that will return errors on parsing after calling `json.Unmarshal`

2024-02-26 13:56 UTC, LinMAD commented on boostrap_test.go
>  	err := StartDatadog(ddCfg, ConnectionTypeHTTP)
FYI, this test was broken not sure why in CI it's not executed anymore but `StartDatadog accepts the interface now, and then the structure must be passed by a pointer.

2024-02-26 18:19 UTC, nhhagen requested changes
I think we need to look closer at this. Like @bendiknesbo is stating this will break the code everywhere that `DatadogConfig` is used as a value.

Are we sure that we want to commit our selves to support JSON as a way of configuring `go-datadog-lib`. Our new helm chart for deploying services uses environment variables to configure Datadog. I think we should move away from supporting custom configuration methods for `go-Datadog-lib`.

We should probably not discuss the future of `go-datadog-lib` in this PR.

2024-02-26 18:24 UTC, nhhagen commented
I removed the major version label so that we do not accidentally bump the major version of go-datadog-lib.

@arunpoudel how do I disable the major version label. Just breaking the API is not enough to bump a major version in Go. We also need to update the module name as well.

2024-02-27 09:55 UTC, LinMAD commented on boostrap_test.go
>  	err := StartDatadog(ddCfg, ConnectionTypeHTTP)
Could be was not thinking about that actually

2024-02-27 12:27 UTC, LinMAD commented
@nhhagen Closing this PR since in the future there are plans to provide the functionality to load configuration with env vars for Datadog so at this point implementing unmarshal does not give much value, since it will be still open for modification via the interface.

2024-02-27 12:27 UTC, closed without merging

2024-02-27 21:14 UTC, arunpoudel commented
> I removed the major version label so that we do not accidentally bump the major version of go-datadog-lib.
> 
> @arunpoudel how do I disable the major version label. Just breaking the API is not enough to bump a major version in Go. We also need to update the module name as well.

I will work on it next techdebt day.

https://github.com/coopnorge/github-workflow-release-drafter/issues/45